enyo.depends(
	"source/CharacterInfo.js",
  "source/CharacterList.js",
  "source/CharacterListItem.js",
	"source/CharacterSheet.js",
	"source/CountdownTimer.js",
	"source/DbSetup.js",
	"source/EveSkillQueue.css",
	"source/EveSkillQueue.js",
	"source/Preferences.js",
	"source/SkillInTraining.js",
	"source/SkillTree.js",
  "source/SkillQueueUpdater.js",
  "source/TimeDiffCalculator.js"
);
